

#define WIFI_SSID    "YOUR_WIFI_NAME"
#define WIFI_PASS    "YOUR_WIFI_PASSWORD"
#define APP_KEY      "YOUR_APP_KEY"
#define APP_SECRET   "YOUR_APP_SECRET"

#define DEVICE_ALL_LIGHTS  "DEVICE_ID_1"
#define DEVICE_MOVIE_MODE  "DEVICE_ID_2"
#define DEVICE_PARTY_MODE  "DEVICE_ID_3"
